#!/usr/bin/env bash

LIGHT=$(printf "%.0f\n" `light -G`)

if [[ ("$LIGHT" -ge "0") && ("$LIGHT" -le "25") ]]; then
	printf "^C3^ 󰃞 ^d^ $LIGHT%%"
elif [[ ("$LIGHT" -ge "25") && ("$LIGHT" -le "50") ]]; then
	printf "^C3^ 󰃝 ^d^ $LIGHT%%"
elif [[ ("$LIGHT" -ge "50") && ("$LIGHT" -le "75") ]]; then
	printf "^C3^ 󰃟 ^d^ $LIGHT%%"
elif [[ ("$LIGHT" -ge "75") && ("$LIGHT" -le "100") ]]; then
	printf "^C3^ 󰃠 ^d^ $LIGHT%%"
fi

case "$BLOCK_BUTTON" in
	4) /usr/share/archcraft/dwm/scripts/dwm_brightness --inc ;;
    5) /usr/share/archcraft/dwm/scripts/dwm_brightness --dec ;;
esac
