#!/usr/bin/env bash

icon=""
brightness=$(light)
current=$(printf "%.0f" $brightness)

echo "^C3^$icon  ^d^$current%"

case "$BLOCK_BUTTON" in
	4) brightness --inc ;;
    5) brightness --dec ;;
esac
