#!/usr/bin/env bash


icon=""
dayofweek=`date +%A`
dayofmonth=`date +%e`
month=`date +%B`
year=`date +%Y`

case $dayofmonth in
    " 1" | 21 | 31)
        suffix="st"
        ;;
    " 2" | 22)
        suffix="nd"
        ;;
    " 3" | 23)
        suffix="rd"
        ;;
    *)
        suffix="th"
        ;;
esac

fulldate="$dayofweek $dayofmonth$suffix of $month $year"

case $BLOCK_BUTTON in
    1) notify-send "$fulldate" ;;
    3) setsid --fork alacritty --class "calcurse,calcurse" -e calcurse ;;
esac


printf "^C4^$icon^d^$(date '+%l:%M%P') "
