#!/usr/bin/env bash

# updates=`checkupdates | wc -l`
updates=$({ timeout 20 doas xbps-install -un 2>/dev/null || true; } | wc -l) # void
# updates=$({ timeout 20 aptitude search '~U' 2>/dev/null || true; } | wc -l)  # apt (ubuntu, debian etc)

case $BLOCK_BUTTON in
    1) setsid --fork ghostty --x11-instance-name=floaterm -e doas xbps-install -Su ;;
esac


if [ "$updates" -eq "0" ]; then
  printf "^c#98c378^    UTD"
else
  printf "^c#e06c75^    $updates"
fi

