#!/usr/bin/env bash

source colors.txt

case "$BLOCK_BUTTON" in
    1) setsid --fork pavucontrol ;;
    3) /usr/share/archcraft/dwm/scripts/dwm_volume --toggle ;;
    4) /usr/share/archcraft/dwm/scripts/dwm_volume --inc ;;
    5) /usr/share/archcraft/dwm/scripts/dwm_volume --dec ;;
esac
current=`pulsemixer --get-volume | cut -d' ' -f1`
status=`pulsemixer --get-mute`

if [ "$current" -gt 40 ]; then
    icon=" "
elif [ "$volume" -gt 15 ]; then
    icon=" "
else
    icon=" "
fi


if [[ "$status" -eq "1" ]]; then
    echo "$gray3󰖁 Muted"
else
    echo "$green$icon $current%"
fi
