#!/usr/bin/env bash


case "$BLOCK_BUTTON" in
    1) setsid --fork pavucontrol ;;
    3) volume --toggle ;;
    4) volume --inc ;;
    5) volume --dec ;;
esac
current=`pulsemixer --get-volume | cut -d' ' -f1`
status=`pulsemixer --get-mute`

if [ "$current" -gt 40 ]; then
    icon=" "
elif [ "$volume" -gt 15 ]; then
    icon=" "
else
    icon=" "
fi


if [[ "$status" -eq "1" ]]; then
    echo "󰖁"
else
    echo "$icon"
fi
